name: Sync to Hugging Face hub
on:
  # push:
  repository_dispatch:
    types: [custom_event_type]
    branches: [main]

  # to run this workflow manually from the Actions tab
  # workflow_dispatch: xxx
  # https://codeburst.io/using-github-actions-with-repository-dispatch-event-c113a45b3948
  
jobs:
  # sync-to-hub:
  customEventType:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://mikeeee:$HF_TOKEN@huggingface.co/spaces/mikeee/ultimatumbee-ng main